### ISSUE TITLE
Writing capability implemented?

### ISSUE THREAD

**Issue by markerikson** [TimSC/mbtiles-cpp#2]
The repo description says it can read _and_ write MBTiles files, but I'm only seeing source implementation for reading.  Anything I'm missing, or is that not actually implemented?

**Comment by TimSC** [comment]
Looks like you are right. I guess I planned to do it but never finished it. I could throw something together if you are interested?

**Comment by markerikson** [comment]
Yeah.  I suspect it's not overly complicated, but seeing more examples would be nice.

Ultimately, what I'm _really_ interested in is figuring out how to add MBTiles writing capability to the https://github.com/geo-data/cesium-terrain-builder project, so I was looking around for examples of writing MBTiles files in C++ for point of reference.

**Comment by TimSC** [comment]
If you are trying to understand the MBTile format, the reader is a good place to start. I'll update the docs to clarify what has been implemented.
