### ISSUE TITLE
build error in protoc version?

### ISSUE THREAD

**Issue by kathur2rain** [TimSC/mbtiles-cpp#3]
----------------------im new to cpp and I can't read the error message... 
----------------------below are part of the error message
In file included from /mbtiles-cpp/Source/vector_tile21/vector_tile.pb.cc:5:0:
/mbtiles-cpp/Source/vector_tile21/../../Include/vector_tile21/vector_tile.pb.h:17:2: error: 
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.

/mbtiles-cpp/Source/vector_tile21/vector_tile.pb.cc: In function 'void vector_tile::protobuf_AssignDesc_vector_5ftile_2eproto()':
/mbtiles-cpp/Source/vector_tile21/vector_tile.pb.cc:60:19: error: no matching function for call to 'google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, vector_tile::Tile*&, const int [1], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)'
       sizeof(Tile));

In file included from /usr/include/google/protobuf/stubs/common.h:41:0,
                 from /mbtiles-cpp/Source/vector_tile21/../../Include/vector_tile21/vector_tile.pb.h:9,
                 from /mbtiles-cpp/Source/vector_tile21/vector_tile.pb.cc:5:
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/include/google/protobuf/generated_message_reflection.h:574:3: note:   candidate expects 1 argument, 9 provided
In file included from /mbtiles-cpp/Source/vector_tile21/vector_tile.pb.cc:14:0:
/usr/include/google/protobuf/generated_message_reflection.h:169:3: note: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by TimSC** [comment]
mbtiles uses the protoc library but some source files in the mbtiles project need to match the protoc version you plan to use. You might need to regenerate the files in the vector_tile21 folder.

To update the protobuf files, get vector_tile.proto from https://github.com/mapbox/vector-tile-spec, remove the line "option optimize_for = LITE_RUNTIME;", then in mbtiles:

cd source/

rm -R vector_tiles21

mkdir vector_tile21

protoc vector_tile.proto --cpp_out vector_tile21

Let me know if you get stuck.

**Comment by kathur2rain** [comment]
thanks for the reply, I'll try to solve it, close for now
